Added new options

diff --git a/epi_reg b/epi_reg
--- a/epi_reg
+++ b/epi_reg
@@ -1,51 +1,221 @@
 #!/bin/sh
 
 Usage() {
-  echo "Usage: `basename $0` <EPI image> <wholehead T1 image> <brain extracted T1 image> <output name>"
-  echo "       `basename $0` <EPI image> <wholehead T1 image> <brain extracted T1 image> <output name> <fieldmap rad/s> <wholehead fieldmap mag> <brain extracted fieldmap mag> <EPI echo spacing (dwell time)> <pe dir> [refweight]"
-  echo " "
-  echo "Second case is when using fieldmaps: echo spacing (dwell time) in seconds; phase encoding direction = x/y/z/-x/-y/-z" 
+    echo ""
+    echo "Usage: `basename $0` [options] --epi=<EPI image> --t1=<wholehead T1 image> --t1brain=<brain extracted T1 image> --out=<output name>"
+    echo " "
+    echo "Optional arguments"
+    echo "  --fmap=<image>         : fieldmap image (in rad/s)"
+    echo "  --fmapmag=<image>      : fieldmap magnitude image - wholehead extracted"
+    echo "  --fmapmagbrain=<image> : fieldmap magnitude image - brain extracted"
+    echo "  --echospacing=<val>    : Effective EPI echo spacing (sometimes called dwell time) - in seconds"
+    echo "  --pedir=<dir>          : phase encoding direction, dir = x/y/z/-x/-y/-z"
+    echo "  --weight=<image>       : weighting image (in T1 space)"
+    echo "  --noclean              : do not clean up intermediate files"
+    echo "  -v                     : verbose output"
+    echo "  -h                     : display this help message"
+    echo " "
+    echo "e.g.:  `basename $0` --epi=example_func --t1=struct --t1brain=struct_brain --out=epi2struct --fmap=fmap_rads --fmapmag=fmap_mag --fmapmagbrain=fmap_mag_brain --echospacing=0.0005 --pedir=-y"
+    echo " "
+    echo "Note that if parallel acceleration is used in the EPI acquisition then the *effective* echo spacing is the actual echo spacing between acquired lines in k-space divided by the acceleration factor."
+    echo " "
+    exit 1
 }
 
-if [ $# -lt 4 ] ; then
-    Usage
-    exit 0;
-fi
 
-vepi=`$FSLDIR/bin/remove_ext $1`;
-vrefhead=`$FSLDIR/bin/remove_ext $2`;
-vrefbrain=`$FSLDIR/bin/remove_ext $3`;
-vout=`$FSLDIR/bin/remove_ext $4`;
+
+get_opt1() {
+    arg=`echo $1 | sed 's/=.*//'`
+    echo $arg
+}
+
+
+get_arg1() {
+    if [ X`echo $1 | grep '='` = X ] ; then 
+	echo "Option $1 requires an argument" 1>&2
+	exit 1
+    else 
+	arg=`echo $1 | sed 's/.*=//'`
+	if [ X$arg = X ] ; then
+	    echo "Option $1 requires an argument" 1>&2
+	    exit 1
+	fi
+	echo $arg
+    fi
+}
+
+get_imarg1() {
+    arg=`get_arg1 $1`;
+    arg=`$FSLDIR/bin/remove_ext $arg`;
+    echo $arg
+}
+
+get_arg2() {
+    if [ X$2 = X ] ; then
+	echo "Option $1 requires an argument" 1>&2
+	exit 1
+    fi
+    echo $2
+}
+
+
+# list of variables to be set via the options
+vepi="";
+vrefhead="";
+vrefbrain="";
+vout="";
 use_fmap=no;
 use_weighting=no;
+verbose=no
+cleanup=yes;
+fmaprads="";
+fmapmaghead="";
+fmapmagbrain="";
+dwell="";
+pe_dir="";
+fdir="y";
 
-if [ $# -ge 9 ] ; then
-    use_fmap=yes;
-    fmaprads=`$FSLDIR/bin/remove_ext $5`;
-    fmapmaghead=`$FSLDIR/bin/remove_ext $6`;
-    fmapmagbrain=`$FSLDIR/bin/remove_ext $7`;
-    dwell=$8;
-    # These are consistent with the ones used in FUGUE (this has been checked)
-    if [ $9 = "x" ] ; then pe_dir=1; fdir="x"; fi
-    if [ $9 = "y" ] ; then pe_dir=2; fdir="y"; fi
-    if [ $9 = "z" ] ; then pe_dir=3; fdir="z"; fi
-    if [ $9 = "-x" ] ; then pe_dir=-1; fdir="x-"; fi
-    if [ $9 = "-y" ] ; then pe_dir=-2; fdir="y-"; fi
-    if [ $9 = "-z" ] ; then pe_dir=-3; fdir="z-"; fi
-    if [ $9 = "x-" ] ; then pe_dir=-1; fdir="x-"; fi
-    if [ $9 = "y-" ] ; then pe_dir=-2; fdir="y-"; fi
-    if [ $9 = "z-" ] ; then pe_dir=-3; fdir="z-"; fi
-    if [ X${pe_dir} = X ] ; then
-	echo "Error: invalid phase encode direction specified";
-	exit 2;
+
+# Parse them baby
+
+if [ $# -lt 4 ] ; then Usage; exit 0; fi
+while [ $# -ge 1 ] ; do
+    iarg=`get_opt1 $1`;
+    case "$iarg"
+	in
+	--epi)
+	    vepi=`get_imarg1 $1`;
+	    shift;;
+	--t1)
+	    vrefhead=`get_imarg1 $1`;
+	    shift;;
+	--t1brain)
+	    vrefbrain=`get_imarg1 $1`;
+	    shift;;
+	--fmap)
+	    fmaprads=`get_imarg1 $1`;
+	    use_fmap=yes; 
+	    shift;;
+	--fmapmag)
+	    fmapmaghead=`get_imarg1 $1`;
+	    shift;;
+	--fmapmagbrain)
+	    fmapmagbrain=`get_imarg1 $1`;
+	    shift;;
+	--out)
+	    vout=`get_imarg1 $1`;
+	    shift;;
+	--echospacing)
+	    dwell=`get_arg1 $1`;
+	    if [ `echo "$dwell > 0.2" | bc -l` = 1 ] ; then 
+		msdwell=`echo "scale=6; $dwell / 1000.0" | bc -l`;
+		echo "Echo spacing should be specified in seconds, not milliseconds.  Value of $dwell appears to be incorrectly specified in milliseconds.  Try using the value $msdwell instead."; 
+		exit 1; 
+	    fi
+	    shift;;
+	--pedir)
+	    pearg=`get_arg1 $1`;
+            # These are consistent with the ones used in FUGUE (this has been checked)
+	    if [ $pearg = "x" ] ; then pe_dir=1; fdir="x"; fi
+	    if [ $pearg = "y" ] ; then pe_dir=2; fdir="y"; fi
+	    if [ $pearg = "z" ] ; then pe_dir=3; fdir="z"; fi
+	    if [ $pearg = "-x" ] ; then pe_dir=-1; fdir="x-"; fi
+	    if [ $pearg = "-y" ] ; then pe_dir=-2; fdir="y-"; fi
+	    if [ $pearg = "-z" ] ; then pe_dir=-3; fdir="z-"; fi
+	    if [ $pearg = "x-" ] ; then pe_dir=-1; fdir="x-"; fi
+	    if [ $pearg = "y-" ] ; then pe_dir=-2; fdir="y-"; fi
+	    if [ $pearg = "z-" ] ; then pe_dir=-3; fdir="z-"; fi
+	    if [ X${pe_dir} = X ] ; then
+		echo "Error: invalid phase encode direction specified";
+		exit 2;
+	    fi
+	    shift;;
+	--weight)
+	    refweight=`get_imarg1 $1`;
+	    use_weighting=yes; 
+	    echo REFWEIGHT = $refweight;
+	    shift;;
+	--noclean)
+	    cleanup=no; 
+	    shift;;
+	-v)
+	    verbose=yes; 
+	    shift;;
+	-h)
+	    Usage;
+	    exit 0;;
+	*)
+	    #if [ `echo $1 | sed 's/^\(.\).*/\1/'` = "-" ] ; then 
+	    echo "Unrecognised option $1" 1>&2
+	    exit 1
+	    #fi
+	    #shift;;
+    esac
+done
+
+### Sanity checking of arguments
+
+if [ X$vout = X ] ; then
+  echo "The compulsory argument --out MUST be used"
+  exit 1;
+fi
+
+if [ X$vepi = X ] ; then
+  echo "The compulsory argument --epi MUST be used"
+  exit 1;
+fi
+
+if [ X$vrefhead = X ] ; then
+  echo "The compulsory argument --t1 MUST be used"
+  exit 1;
+fi
+
+if [ X$vrefbrain = X ] ; then
+  echo "The compulsory argument --t1brain MUST be used"
+  exit 1;
+fi
+
+if [ $use_fmap = yes ] ; then
+    if [ X$fmaprads = X ] ; then
+	echo "The argument --fmap MUST be usspecifieded if using fieldmaps"
+	exit 1;
     fi
-    if [ $# -ge 10 ] ; then refweight="${10}"; use_weighting=yes; echo REFWEIGHT = $refweight ; fi
-else
-    if [ $# -ne 4 ] ; then
-	Usage
+    if [ X$fmapmaghead = X ] ; then
+	echo "The argument --fmapmag MUST be specified if using fieldmaps"
+	exit 1;
+    fi
+    if [ X$fmapmagbrain = X ] ; then
+	echo "The argument --fmapmagbrain MUST be specified if using fieldmaps"
+	exit 1;
+    fi
+    if [ X$pe_dir = X ] ; then
+	echo "The argument --pedir MUST be specified if using fieldmaps"
+	exit 1;
+    fi
+    if [ X$dwell = X ] ; then
+	echo "The argument --echospacing MUST be specified if using fieldmaps"
 	exit 1;
     fi
 fi
+
+if [ $verbose = yes ] ; then
+    echo "Arguments are:"
+    echo "  vepi = $vepi"
+    echo "  vrefhead = $vrefhead"
+    echo "  vrefbrain = $vrefbrain"
+    echo "  vout = $vout"
+    echo "  fmaprads = $fmaprads"
+    echo "  fmapmaghead = $fmapmaghead"
+    echo "  fmapmagbrain = $fmapmagbrain"
+    echo "  dwell = $dwell"
+    echo "  pe_dir = $pe_dir"
+    echo "  fdir = $fdir"
+    echo "  use_fmap = $use_fmap"
+    echo "  use_weighting = $use_weighting"
+fi
+
+##########################################################################################
+
 
 # create the WM segmentation
 if [ `$FSLDIR/bin/imtest ${vrefbrain}_wmseg` = 0 ] ; then
@@ -54,7 +224,8 @@ if [ `$FSLDIR/bin/imtest ${vrefbrain}_wmseg` = 0 ] ; then
     $FSLDIR/bin/fslmaths ${vout}_fast_pve_2 -thr 0.5 -bin ${vout}_fast_wmseg
 else
     for file in ${vrefbrain}_wmseg*; do
-	ln -s ${vout}_fast_wmseg${file/${vrefbrain}_wmseg/} #To link the correct files with extensions
+	absfile=`readlink -f $file`;
+	ln -s $file ${vout}_fast_wmseg${absfile/${vrefbrain}_wmseg/} #To link the correct files with extensions
     done
 fi
 # make a WM edge map for visualisation (good to overlay in FSLView)
@@ -62,7 +233,8 @@ if [ `$FSLDIR/bin/imtest ${vrefbrain}_wmedge` = 0 ] ; then
   $FSLDIR/bin/fslmaths ${vout}_fast_wmseg -edge -bin -mas ${vout}_fast_wmseg ${vout}_fast_wmedge
 else
     for file in ${vrefbrain}_wmedge*; do
-	ln -s ${vout}_fast_wmedge${file/${vrefbrain}_wmedge/} #To link the correct files with extensions
+	absfile=`readlink -f $file`;
+	ln -s ${vout}_fast_wmedge${absfile/${vrefbrain}_wmedge/} #To link the correct files with extensions
     done
 fi
 
@@ -120,7 +292,9 @@ fi
 ####################
 
 # TODO - CLEAN UP UNNECESSARY FILES
-$FSLDIR/bin/imrm ${vout}_fast_mixeltype ${vout}_fast_pve* ${vout}_fast_seg ${vout}_fast_wmseg 
-$FSLDIR/bin/imrm ${vout}_fieldmap*mask* ${vout}_fieldmap2str_pad0
+if [ $cleanup = yes ] ; then
+    $FSLDIR/bin/imrm ${vout}_fast_mixeltype ${vout}_fast_pve* ${vout}_fast_seg ${vout}_fast_wmseg 
+    $FSLDIR/bin/imrm ${vout}_fieldmap*mask* ${vout}_fieldmap2str_pad0
+fi
 
 
